codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "android/**"
  - "**/*.md"
  - "**/*.sh"
  - "**/test_*.py"
  - "**/test_*.js"
  - "**/test_*.ts"
  - "**/Test*.java"
  - "rust/src/main.rs"

flags:
  python:
    paths:
      - python/
    carryforward: true
    
  cpp:
    paths:
      - cpp/
    carryforward: true
    
  java:
    paths:
      - java/
    carryforward: true
    
  javascript:
    paths:
      - javascript/
    carryforward: true
    
  typescript:
    paths:
      - typescript/
    carryforward: true
    
  rust:
    paths:
      - rust/
    carryforward: true
